/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author matti
 */
public class FPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FPrincipal
     */
    public FPrincipal() {
        initComponents();
        cerrar();
        setIconImage(new ImageIcon(getClass().getResource("/vista/logo.jpg")).getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo1 = new javax.swing.ButtonGroup();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        miCerrar = new javax.swing.JMenuItem();
        miMatrices = new javax.swing.JMenuItem();
        miCuenta = new javax.swing.JMenuItem();
        rbOscuro = new javax.swing.JRadioButton();
        titulo = new javax.swing.JLabel();
        bMatrices = new javax.swing.JButton();
        bCuenta = new javax.swing.JButton();
        cbIngles = new javax.swing.JCheckBox();
        Idioma = new javax.swing.JLabel();
        cbEspañol = new javax.swing.JCheckBox();
        bMayor = new javax.swing.JButton();

        miCerrar.setText("Cerrar");
        miCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCerrarActionPerformed(evt);
            }
        });
        jPopupMenu2.add(miCerrar);

        miMatrices.setText("Matrices");
        jPopupMenu2.add(miMatrices);

        miCuenta.setText("Cuenta");
        jPopupMenu2.add(miCuenta);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());

        rbOscuro.setText("Modo Oscuro");
        rbOscuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOscuroActionPerformed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        titulo.setText("Pagina Principal");

        bMatrices.setText("Matrices");
        bMatrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMatricesActionPerformed(evt);
            }
        });

        bCuenta.setText("Cuenta caracteres");
        bCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCuentaActionPerformed(evt);
            }
        });

        Grupo1.add(cbIngles);
        cbIngles.setText("Ingles");
        cbIngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbInglesActionPerformed(evt);
            }
        });

        Idioma.setText("Idioma Pagina Principal");

        Grupo1.add(cbEspañol);
        cbEspañol.setText("Español");
        cbEspañol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEspañolActionPerformed(evt);
            }
        });

        bMayor.setText("Mayor menor");
        bMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMayorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(titulo)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bMayor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bMatrices, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bCuenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Idioma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbEspañol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(rbOscuro, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(cbIngles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbOscuro)
                    .addComponent(titulo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bMatrices)
                    .addComponent(Idioma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbIngles)
                    .addComponent(bCuenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEspañol)
                    .addComponent(bMayor))
                .addContainerGap(173, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_miCerrarActionPerformed
/**
 * Metodo que ejecuta la ventana vinculada al boton
 * @param evt 
 */
    private void bCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCuentaActionPerformed
        // TODO add your handling code here:
        Ventana3 newframe = new Ventana3();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bCuentaActionPerformed

    /**
 * Metodo que cambia el texto de los botones si el checkbox esta selecionado
 * @param evt 
 */
    private void cbInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbInglesActionPerformed
        // TODO add your handling code here:
        if (cbIngles.isSelected()) {
            titulo.setText("Main Menu");
            Idioma.setText("Main Menu Language");
            rbOscuro.setText("Dark mode");
            bCuenta.setText("Character count");
            bMatrices.setText("Arrays");
            cbEspañol.setText("Spanish");
            cbIngles.setText("English");
            bMayor.setText("Major minor");
        }
    }//GEN-LAST:event_cbInglesActionPerformed
/**
 * Metodo que ejecuta la ventana vinculada al boton
 * @param evt 
 */
    private void bMatricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMatricesActionPerformed
        // TODO add your handling code here:
        Ventana2 newframe = new Ventana2();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bMatricesActionPerformed
/**
 * Metodo que cuando pulsas el radio button cambia el color de la página
 * @param evt 
 */
    private void rbOscuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOscuroActionPerformed
        // TODO add your handling code here:
        if (rbOscuro.isSelected()) {
            this.getContentPane().setBackground(Color.GRAY);
        }else{
            this.getContentPane().setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_rbOscuroActionPerformed
/**
 * Metodo que cambia el texto de los botones si el checkbox esta selecionado
 * @param evt 
 */
    private void cbEspañolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEspañolActionPerformed
        // TODO add your handling code here:
        if (cbEspañol.isSelected()) {
            titulo.setText("Pagina Principal");
            Idioma.setText("Idioma Pagina Principal");
            rbOscuro.setText("Modo oscuro");
            bCuenta.setText("Cuenta Caracteres");
            bMatrices.setText("Matrices");
            cbEspañol.setText("Español");
            cbIngles.setText("Ingles");
            bMayor.setText("Mayor menor");
        }
    }//GEN-LAST:event_cbEspañolActionPerformed
/**
 * Metodo que ejecuta la ventana vinculada al boton
 * @param evt 
 */
    private void bMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMayorActionPerformed
        // TODO add your handling code here:
        Ventana4 newframe = new Ventana4();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bMayorActionPerformed

    /**
     * Metodos que ejecuta una ventana de confirmación si quieres cerrar la ventana
     */
    public void cerrar(){
        try {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter(){
                public void windowClosing(WindowEvent e) {
                    confirmarSalida();
                }
            });
            this.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void confirmarSalida(){
        int valor = JOptionPane.showConfirmDialog(this, "¿Estas seguro de cerrar?", "Advertencia",JOptionPane.YES_NO_OPTION);
        if (valor == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Grupo1;
    private javax.swing.JLabel Idioma;
    private javax.swing.JButton bCuenta;
    private javax.swing.JButton bMatrices;
    private javax.swing.JButton bMayor;
    private javax.swing.JCheckBox cbEspañol;
    private javax.swing.JCheckBox cbIngles;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JMenuItem miCerrar;
    private javax.swing.JMenuItem miCuenta;
    private javax.swing.JMenuItem miMatrices;
    private javax.swing.JRadioButton rbOscuro;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
